/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3f4",
        secondary: "#954071",
        "on-surface": "#1a1c1d",
        "on-error": "#ffffff",
        "on-primary-fixed": "#3c002a",
        outline: "#85727a",
        "surface-tint": "#983d74",
        "outline-variant": "#d7c1ca",
        "surface-bright": "#f9f9fa",
        "primary-fixed-dim": "#ffaed9",
        "secondary-fixed-dim": "#ffafd6",
        "on-secondary-fixed": "#3c0028",
        "inverse-on-surface": "#f0f1f2",
        "on-background": "#1a1c1d",
        "on-secondary": "#ffffff",
        "on-primary-container": "#ffaed9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#782858",
        "on-secondary-container": "#7b2b5a",
        "on-surface-variant": "#52424a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffaed8",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#893168",
        "secondary-fixed": "#ffd8e8",
        "on-tertiary-fixed": "#3c002a",
        background: "#f9f9fa",
        "on-primary-fixed-variant": "#7a255c",
        "inverse-primary": "#ffaed9",
        "surface-container-highest": "#e2e2e3",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e8e8e9",
        "on-tertiary-container": "#ffaed8",
        "surface-variant": "#e2e2e3",
        "error-container": "#ffdad6",
        primary: "#6c1850",
        "primary-fixed": "#ffd8e9",
        "tertiary-fixed": "#ffd8e9",
        "surface-container": "#eeeeef",
        "tertiary-container": "#823864",
        tertiary: "#66204c",
        "secondary-container": "#ff99ce",
        "inverse-surface": "#2f3132",
        error: "#ba1a1a",
        surface: "#f9f9fa",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#742c58",
        border: "#d7c1ca",
        input: "#d7c1ca",
        ring: "#983d74",
        foreground: "#1a1c1d",
        muted: "#eeeeef",
        "muted-foreground": "#52424a",
        card: "#ffffff",
        "card-foreground": "#1a1c1d",
        popover: "#ffffff",
        "popover-foreground": "#1a1c1d",
        accent: "#ffd8e8",
        "accent-foreground": "#3c0028",
        destructive: "#ba1a1a",
        "primary-foreground": "#ffffff",
        "secondary-foreground": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "title-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "0", fontWeight: "700" }],
      },
      boxShadow: {
        dashboard: "0 24px 70px rgba(26, 28, 29, 0.18)",
      },
    },
  },
  plugins: [],
}
